### ISSUE TITLE
incorrect client update modal/download/instructions for linux client

### ISSUE THREAD

**Issue by faust64** [PeerioTechnologies/peerio-client#330]
This is based on my recollections, last time we updated the client. Sorry for being vague.

Running an outdated version of our desktop client, a message shows up, inviting us to update, eventually downloading something from peerio.com.
Instead, we should display some message reminding users to update via their package manager (apt, yum, ...). We could prepare a message per distro family, or at the very least add something to the repository docs.

**Comment by faust64** [comment]
As of today (and since 1.2.2 I suppose), when I start my packaged client, I'm told that "une mise à jour essentielle est disponible".
When I click on the download link, it opens some lightweight browser ("Web" 3.14.1, powered by webkit) and downloads peerio-mac.zip.
About half way of my download, I get some 'Error downloading: Connection terminated unexpectedly'.

Desktop clients should not be subjected to the same messages as browser-embedded clients.
Especially when we skip a Linux version.

**Comment by faust64** [comment]
Also: the only way I have to close the popup and start using my app as expected, is to press Escape.
no close button, clicking out of the popup doesn't make it disappear, ... it's not obvious.

**Comment by faust64** [comment]
uh... can't connect?

**Comment by faust64** [comment]
fixed thanks to floh.
My bad: I pushed the last commit from staging, instead of the one from master, ... shame on me...

still, the pop-up thing remain a problem, ... pending further investigations.

**Comment by flohdot** [comment]
Right, we need to change those instructions for the Linux client. And I just fixed the 1.2.1 vs 1.2.2 problem manually, might take a bit to propagate. You'll still see an update but it won't me mandatory.

**Comment by faust64** [comment]
lost sight of that one.
as far as I remember, we're done with this issue, closing.
